# -------------------------------------------------------------------------
# This file is part of the MindStudio project.
# Copyright (c) 2025-2026 Huawei Technologies Co.,Ltd.
#
# MindStudio is licensed under Mulan PSL v2.
# You can use this software according to the terms and conditions of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
#
#          `http://license.coscl.org.cn/MulanPSL2`
#
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.

import argparse
import json
import logging
import shutil
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from textwrap import dedent
from typing import Any, Dict, List, Set, Tuple

from . import CmdStrategy, CmdType


logger = logging.getLogger(__name__)


def setup_compare(subparsers: argparse._SubParsersAction, parents=None):
    if parents is None:
        parents = []
    desc = dedent("""\
        COMPARE - Compare the results of multiple msprechecker dump runs.

        This command compares the outputs (JSON files) generated by previous runs of msprechecker dump.
        It highlights differences in both the main check results and configuration sections.

        Typical use cases:
            - Regression testing between different environments or code versions.
            - Verifying consistency across multiple deployments.
    """)

    epilog = dedent("""\
        Examples:
            msprechecker compare result_a.json result_b.json
            msprechecker compare ./out1.json ./out2.json ./out3.json
    """)

    compare_parser = subparsers.add_parser(
        CmdType.COMPARE.value,
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=desc,
        usage="msprechecker compare FILE1 FILE2 [FILE3 ...]",
        epilog=epilog,
        help="Compare the results of multiple msprechecker dump runs",
        parents=parents,
    )
    compare_parser.add_argument(
        "dumped_path",
        nargs="+",
        metavar="FILE",
        help="Paths to msprechecker output JSON files to compare (at least two required)",
    )
    return compare_parser


# Sentinel object representing a key that is absent in a particular file.
# Defined at module level so both ConfigComparator and DiffEntry can reference
# it without either class depending on the other.
MISSING = object()


@dataclass
class DiffEntry:
    """Represents a difference at a specific path across multiple files.

    values_by_file maps file path -> value, where value may be the module-level
    MISSING sentinel if the key was absent in that file. Consumers should check
    `value is MISSING` rather than comparing against None.
    """

    path: Tuple
    # Sorted at construction time so output order is deterministic regardless
    # of the order configs were loaded.
    values_by_file: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self):
        self.values_by_file = dict(sorted(self.values_by_file.items()))

    @property
    def path_str(self) -> str:
        """Human-readable dot/bracket path representation."""
        parts = []
        for part in self.path:
            if isinstance(part, int):
                parts.append(f"[{part}]")
            else:
                parts.append(f".{part}" if parts else part)
        return "".join(parts)

    @property
    def has_differences(self) -> bool:
        if not self.values_by_file:
            return False
        values = list(self.values_by_file.values())
        return not all(v == values[0] for v in values)


@dataclass
class ComparisonResult:
    """Results of comparing multiple configuration files."""

    file_paths: List[str]
    differences_by_type: Dict[str, List[DiffEntry]]

    @property
    def has_differences(self) -> bool:
        return any(diffs for diffs in self.differences_by_type.values())

    @property
    def total_differences(self) -> int:
        return sum(len(diffs) for diffs in self.differences_by_type.values())


class ConfigFlattener:
    """Flattens and unflattens nested config structures."""

    # Keys whose values are always treated as leaves (not recursed into).
    LEAF_KEYS = {"npuDeviceIds"}

    @classmethod
    def flatten(cls, data: Any, path: Tuple = ()) -> Dict[Tuple, Any]:
        """Flatten a nested structure to a path->value mapping.

        Uses an explicit stack to avoid recursion limits on deep structures.
        Dict keys are pushed in reverse order so they are popped (and therefore
        processed) in original insertion order — matching the behaviour of a
        straightforward recursive implementation.
        """
        result: Dict[Tuple, Any] = {}
        stack = [(data, path)]

        while stack:
            current_data, current_path = stack.pop()

            if isinstance(current_data, dict):
                # Push in reverse so the first key is processed first.
                for key in reversed(list(current_data.keys())):
                    value = current_data[key]
                    new_path = current_path + (key,)
                    if key in cls.LEAF_KEYS:
                        result[new_path] = value
                    else:
                        stack.append((value, new_path))

            elif isinstance(current_data, list):
                # Push in reverse to maintain index order after popping.
                for idx in range(len(current_data) - 1, -1, -1):
                    stack.append((current_data[idx], current_path + (idx,)))

            else:
                result[current_path] = current_data

        return result

    @classmethod
    def unflatten(cls, flat_data: Dict[Tuple, Any]) -> Any:
        """Reconstruct a nested structure from a path->value mapping."""
        if not flat_data:
            return {}

        sorted_paths = sorted(flat_data.items(), key=lambda x: x[0])
        root: Dict = {}

        for path, value in sorted_paths:
            if not path:
                continue

            current = root
            for i, key in enumerate(path[:-1]):
                next_key = path[i + 1]

                if isinstance(next_key, int):
                    if key not in current:
                        current[key] = []
                    while len(current[key]) <= next_key:
                        current[key].append({})
                    current = current[key][next_key]
                else:
                    if key not in current:
                        current[key] = {}
                    current = current[key]

            final_key = path[-1]
            if isinstance(current, list):
                while len(current) <= final_key:
                    current.append(None)
            current[final_key] = value

        return root


class ConfigComparator:
    """Compares multiple configuration files and identifies differences."""

    def __init__(self, file_paths: List[str]):
        if len(file_paths) < 2:
            raise ValueError("At least 2 files required for comparison")
        self.file_paths = file_paths
        self.configs: Dict[str, Dict[str, Any]] = {}

    def load_configs(self) -> None:
        """Load all configuration files.

        Raises:
            FileNotFoundError: If any file does not exist.
            json.JSONDecodeError: If any file contains invalid JSON.
        """
        for path in self.file_paths:
            with open(path) as f:
                self.configs[path] = json.load(f)

    def compare(self) -> ComparisonResult:
        """Compare all loaded configs and return a ComparisonResult."""
        # Group each section (e.g. "env", "sys") across all files.
        configs_by_type: Dict[str, Dict[str, Any]] = defaultdict(dict)
        for file_path, config in self.configs.items():
            for conf_type, conf_data in config.items():
                configs_by_type[conf_type][file_path] = conf_data

        differences_by_type = {
            conf_type: self._compare_section(configs)
            for conf_type, configs in configs_by_type.items()
        }

        return ComparisonResult(
            file_paths=self.file_paths,
            differences_by_type=differences_by_type,
        )

    def _compare_section(self, configs: Dict[str, Any]) -> List[DiffEntry]:
        """Find all differing paths within a single config section."""
        flattened = {
            file_path: ConfigFlattener.flatten(config)
            for file_path, config in configs.items()
        }

        all_paths: Set[Tuple] = set()
        for flat_config in flattened.values():
            all_paths.update(flat_config.keys())

        differences = []
        for path in sorted(all_paths):
            values_by_file = {
                file_path: flattened.get(file_path, {}).get(path, MISSING)
                for file_path in self.file_paths
            }
            entry = DiffEntry(path=path, values_by_file=values_by_file)
            if entry.has_differences:
                differences.append(entry)

        return differences


class DiffFormatter:
    """Formats a ComparisonResult for human-readable terminal output."""

    MISSING_DISPLAY = "<<<MISSING>>>"

    def __init__(
        self,
        result: ComparisonResult,
        verbose: bool = False,
        max_display_len: int = 30,
    ):
        self.result = result
        self.term_width = shutil.get_terminal_size().columns
        self.verbose = verbose
        self.max_display_len = max_display_len

    def format_summary(self) -> str:
        lines = [f"Files compared: {len(self.result.file_paths)}"]
        for i, path in enumerate(self.result.file_paths, 1):
            lines.append(f"  [{i}] {path}")
        lines.append(f"\nTotal differences: {self.result.total_differences}")
        return "\n".join(lines)

    def format_differences(self) -> str:
        if not self.result.has_differences:
            return self._section_header("ALL FILES IDENTICAL")

        lines = []
        for conf_type in sorted(self.result.differences_by_type.keys()):
            diffs = self.result.differences_by_type[conf_type]
            if not diffs:
                continue
            lines.append(self._section_header(f"{conf_type} DIFFERENCES"))
            lines.append(f"Found {len(diffs)} difference(s)")
            for diff in diffs:
                lines.append(self._format_diff_entry(diff))
                lines.append("_ " * (self.term_width // 2))

        return "\n".join(lines)

    def _format_diff_entry(self, diff: DiffEntry) -> str:
        lines = [f"\nPath: {diff.path_str}"]
        for file_path, value in diff.values_by_file.items():
            if value is MISSING:
                display_value = self.MISSING_DISPLAY
            else:
                display_value = json.dumps(value, indent=2)
            short_path = Path(file_path).name
            lines.append(f"  [{short_path}]: {self._shorten(display_value)}")
        return "\n".join(lines)

    def _shorten(self, text: str) -> str:
        try:
            result = repr(text)
        except Exception:
            result = object.__repr__(text)
        if self.verbose or len(result) < self.max_display_len:
            return result
        return result[: self.max_display_len] + " [truncated]..."

    def _section_header(self, title: str) -> str:
        centered = f" {title} ".center(self.term_width, "=")
        return f"\n{centered}\n"


class Compare(CmdStrategy):
    """Command strategy for comparing dumped configuration files."""

    def execute(self, args: Any) -> int:
        try:
            comparator = ConfigComparator(args.dumped_path)
            comparator.load_configs()
            result = comparator.compare()

            formatter = DiffFormatter(result)
            print(formatter.format_summary())
            print(formatter.format_differences())

            return 1 if result.has_differences else 0

        except ValueError:
            logger.exception("Invalid input")
            return 1
        except FileNotFoundError:
            logger.exception("File not found")
            return 1
        except json.JSONDecodeError:
            logger.exception("Invalid JSON in file")
            return 1
        except Exception:
            logger.exception("Unexpected error during comparison")
            return 1
