# -------------------------------------------------------------------------
# This file is part of the MindStudio project.
# Copyright (c) 2025-2026 Huawei Technologies Co.,Ltd.
#
# MindStudio is licensed under Mulan PSL v2.
# You can use this software according to the terms and conditions of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
#
#          `http://license.coscl.org.cn/MulanPSL2`
#
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.

import os
import argparse
from textwrap import dedent

from ..core.collector import Collector
from ..strategies import Image, Weight, Configs, Sys, Env, Ascend
from ..utils import Utils, PreFetch, Output, LOGGER
from ..utils import Framework

from . import CmdStrategy, CmdType


def setup_sync(subparsers: argparse._SubParsersAction, parents=None):
    sync_parser = subparsers.add_parser(
        CmdType.SYNC.value,
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=_get_description(),
        usage="msprechecker sync [EXTRA OPTIONS] <SNAPSHOT PATH>",
        epilog=_get_epilog(),
        help="Replicate a snapshot from 0 to 1",
    )

    _add_sync_arguments(sync_parser)
    _add_extra_options(sync_parser)

    return sync_parser


def _get_description():
    return dedent("""\
        sync - Replicate a snapshot from 0 to 1.

        This command parses a snapshot file (generated by dump command), verify the hardware
        configuration of the current environment, guides the user to download the required
        images and model weights, and provide a one-click start script.
    """)


def _get_epilog():
    return dedent("""\
        Example:
          msprechecker sync '/path/to/snapshot.json'            # Replicate snapshots from '/path/to/snapshot.json'
    """)


def _add_sync_arguments(sync_parser):
    sync_parser.add_argument(
        "snapshot_path",
        metavar="",
        help=(
            "Path to the snapshot file (generated by dump command)."
        ),
    )


def _add_extra_options(sync_parser):
    env_group = sync_parser.add_argument_group("Env Options")
    framework = PreFetch.get_framework()
    if framework == Framework.UNKNOWN:
        Utils.log_error_and_exit("Unsupported image type of container, please exit from the current container.")

    required = framework not in {Framework.HOST, Framework.UNKNOWN}
    env_group.add_argument(
        "-w", "--weight-dir", required=required, default="", metavar="", help="Directory path containing model weights."
    )


class SyncCmd(CmdStrategy):

    def execute(self, args: argparse.Namespace) -> int:
        collector = Collector([Sys(), Ascend(), Weight(weight_dir=args.weight_dir), Image(), Configs(), Env()])
        if PreFetch.get_framework() == Framework.HOST:
            collector.add_strategy(Env())
        abspath = os.path.abspath(args.snapshot_path)
        target_data = Utils.load_json(abspath)
        collector.sync(target_data)

        return 0
