ENABLE=${1-1}
echo "ENABLE=$ENABLE"

if [ "$ENABLE" = "1" ]; then
    export CPU_AFFINITY_CONF=2
    export NPU_MEMORY_FRACTION=0.97
    export TASK_QUEUE_ENABLE=2
    export HCCL_DETERMINISTIC=false
    export HCCL_RDMA_PCIE_DIRECT_POST_NOSTRICT=TRUE
    export MINDIE_LOG_LEVEL=ERROR
    unset ASCEND_LAUNCH_BLOCKING
    export ATB_WORKSPACE_MEM_ALLOC_ALG_TYPE=2
    export ATB_WORKSPACE_MEM_ALLOC_GLOBAL=1
    export PYTORCH_NPU_ALLOC_CONF=expandable_segments:True
else
    unset CPU_AFFINITY_CONF
    unset NPU_MEMORY_FRACTION
    unset TASK_QUEUE_ENABLE
    unset HCCL_DETERMINISTIC
    unset HCCL_RDMA_PCIE_DIRECT_POST_NOSTRICT
    unset MINDIE_LOG_LEVEL
    unset ASCEND_LAUNCH_BLOCKING
    unset ATB_WORKSPACE_MEM_ALLOC_ALG_TYPE
    unset ATB_WORKSPACE_MEM_ALLOC_GLOBAL
    unset PYTORCH_NPU_ALLOC_CONF
fi
